### ISSUE TITLE
Check validation of all inputs on another input change

### ISSUE THREAD

**Issue by luhovskyi** [chainlist/svelte-forms#10] opened 2020-02-27 09:57 UTC
Is there a way to check validation of all form inputs whatever I change any of them?

### Steps to reproduce
1. Type some characters in the first input and make it invalid.
2. Focus second input and starts changing it - type first letter. First input on change of second input becomes valid.

### Expected behavior
1. Type some characters in the first input and make it invalid.
2. Focus second input and starts changing it - type first letter. First input on change of second input **stays invalid**.

**Comment by AnthyG** [comment] 2020-06-02 15:40
This is a duplicate of #8

**Closed** 2020-06-02 16:43 UTC
