### ISSUE TITLE
dependency error when using svelte-forms/validator

### ISSUE THREAD

**Issue by Ak4zh** [chainlist/svelte-forms#56] opened 2022-01-26 18:51 UTC
```
6:31:56 PM [vite] new dependencies found: svelte-forms, svelte-forms/validators, updating...
 > node_modules/websocket/lib/WebSocketRouter.js:18:19: error: Could not read from file: /workspace/transport-app/util
    18 │ var util = require('util');
       ╵                    ~~~~~~

 > node_modules/websocket/lib/WebSocketRouter.js:19:27: error: Could not read from file: /workspace/transport-app/events
    19 │ var EventEmitter = require('events').EventEmitter;
       ╵                            ~~~~~~~~

 > node_modules/websocket/lib/WebSocketRequest.js:17:21: error: Could not read from file: /workspace/transport-app/crypto
    17 │ var crypto = require('crypto');
       ╵                      ~~~~~~~~

 > node_modules/websocket/lib/WebSocketRequest.js:19:18: error: Could not read from file: /workspace/transport-app/url
    19 │ var url = require('url');
       ╵                   ~~~~~

 > node_modules/node-gyp-build/index.js:3:17: error: Could not read from file: /workspace/transport-app/os
    3 │ var os = require('os')
      ╵                  ~~~~

 > node_modules/websocket/lib/WebSocketClient.js:22:20: error: Could not read from file: /workspace/transport-app/https
    22 │ var https = require('https');
       ╵                     ~~~~~~~

 > node_modules/node-gyp-build/index.js:1:17: error: Could not read from file: /workspace/transport-app/fs
    1 │ var fs = require('fs')
      ╵                  ~~~~

 > node_modules/websocket/lib/WebSocketClient.js:21:19: error: Could not read from file: /workspace/transport-app/http
    21 │ var http = require('http');
       ╵                    ~~~~~~

 > node_modules/node-gyp-build/index.js:2:19: error: Could not read from file: /workspace/transport-app/path
    2 │ var path = require('path')
      ╵                    ~~~~~~

 > node_modules/websocket/vendor/FastBufferList.js:7:21: error: Could not read from file: /workspace/transport-app/buffer
    7 │ var Buffer = require('buffer').Buffer;
      ╵                      ~~~~~~~~

 > node_modules/node-fetch/lib/index.mjs:6:17: error: Could not read from file: /workspace/transport-app/zlib
    6 │ import zlib from 'zlib';
      ╵                  ~~~~~~

 > node_modules/node-fetch/lib/index.mjs:1:19: error: Could not read from file: /workspace/transport-app/stream
    1 │ import Stream from 'stream';
      ╵                    ~~~~~~~~

 > node_modules/websocket/node_modules/debug/src/node.js:5:18: error: Could not read from file: /workspace/transport-app/tty
    5 │ var tty = require('tty');
      ╵                   ~~~~~

 > node_modules/websocket/node_modules/debug/src/node.js:193:24: error: Could not read from file: /workspace/transport-app/net
    193 │       var net = require('net');
        ╵                         ~~~~~

6:31:56 PM [vite] error while updating dependencies:
Error: Build failed with 14 errors:
node_modules/node-fetch/lib/index.mjs:1:19: error: Could not read from file: /workspace/transport-app/stream
node_modules/node-fetch/lib/index.mjs:6:17: error: Could not read from file: /workspace/transport-app/zlib
node_modules/node-gyp-build/index.js:1:17: error: Could not read from file: /workspace/transport-app/fs
node_modules/node-gyp-build/index.js:2:19: error: Could not read from file: /workspace/transport-app/path
node_modules/node-gyp-build/index.js:3:17: error: Could not read from file: /workspace/transport-app/os
...
    at failureErrorWithLog (/workspace/transport-app/node_modules/esbuild/lib/main.js:1451:15)
    at /workspace/transport-app/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/workspace/transport-app/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/workspace/transport-app/node_modules/esbuild/lib/main.js:1129:7)
    at /workspace/transport-app/node_modules/esbuild/lib/main.js:1238:14
    at /workspace/transport-app/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/workspace/transport-app/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/workspace/transport-app/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
Cannot read properties of null (reading 'required')
TypeError: Cannot read properties of null (reading 'required')
    at eval (/src/routes/owners/index.svelte:62:78)
    at Object.$$render (/workspace/transport-app/node_modules/svelte/internal/index.js:1684:22)
    at Object.default (root.svelte:38:46)
    at eval (/src/routes/__layout.svelte:39:117)
    at Object.$$render (/workspace/transport-app/node_modules/svelte/internal/index.js:1684:22)
    at root.svelte:36:44
    at $$render (/workspace/transport-app/node_modules/svelte/internal/index.js:1684:22)
    at Object.render (/workspace/transport-app/node_modules/svelte/internal/index.js:1692:26)
    at render_response (file:///workspace/transport-app/node_modules/@sveltejs/kit/dist/ssr.js:481:28)
    at async respond$1 (file:///workspace/transport-app/node_modules/@sveltejs/kit/dist/ssr.js:1334:10)
```

**Comment by chainlist** [comment] 2022-01-27 14:18
Hi,

Can you check in your `package.json` file the `type` property is set to `module`?

**Comment by Ak4zh** [comment] 2022-01-27 15:26
@chainlist  Yes it's set as module.
`"type": "module",`

**Comment by chainlist** [comment] 2022-01-27 15:50
Hi again,

I juste tried myself with the latest version of svelte-kit and it is working perfectly on my side.
It's seems to be more of an issue with the svelte-kit version used by your template.

Latest version of svelte-kit uses an updated version of `vite` to compile and run the code on dev environment. And vite introduced a breaking changes when wanting to be compliant with the ES module import.

Gonna keep looking for what this issues comes from, but IMH better look to update to latest svelte-kit and vite version for the template you are using.

**Comment by chainlist** [comment] 2022-01-27 21:16
Marked as duplicate of #55

**Closed** 2022-02-06 01:07 UTC
Labels: bug, duplicate
